/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as LandingVerifyEmailRouteImport } from './routes/_landing/verify-email'
import { Route as LandingResendVerificationEmailRouteImport } from './routes/_landing/resend-verification-email'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/_landing/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingVerifyEmailRoute = LandingVerifyEmailRouteImport.update({
  id: '/_landing/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingResendVerificationEmailRoute =
  LandingResendVerificationEmailRouteImport.update({
    id: '/_landing/resend-verification-email',
    path: '/resend-verification-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/resend-verification-email': typeof LandingResendVerificationEmailRoute
  '/verify-email': typeof LandingVerifyEmailRoute
  '/': typeof LandingIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/resend-verification-email': typeof LandingResendVerificationEmailRoute
  '/verify-email': typeof LandingVerifyEmailRoute
  '/': typeof LandingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_landing/resend-verification-email': typeof LandingResendVerificationEmailRoute
  '/_landing/verify-email': typeof LandingVerifyEmailRoute
  '/_landing/': typeof LandingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/resend-verification-email'
    | '/verify-email'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/resend-verification-email'
    | '/verify-email'
    | '/'
  id:
    | '__root__'
    | '/_auth/login'
    | '/_auth/register'
    | '/_landing/resend-verification-email'
    | '/_landing/verify-email'
    | '/_landing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  LandingResendVerificationEmailRoute: typeof LandingResendVerificationEmailRoute
  LandingVerifyEmailRoute: typeof LandingVerifyEmailRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/verify-email': {
      id: '/_landing/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof LandingVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/resend-verification-email': {
      id: '/_landing/resend-verification-email'
      path: '/resend-verification-email'
      fullPath: '/resend-verification-email'
      preLoaderRoute: typeof LandingResendVerificationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  LandingResendVerificationEmailRoute: LandingResendVerificationEmailRoute,
  LandingVerifyEmailRoute: LandingVerifyEmailRoute,
  LandingIndexRoute: LandingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
