/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as DemoI18nRouteImport } from './routes/demo.i18n'
import { Route as LandingRegisterRouteImport } from './routes/_landing/register'
import { Route as LandingLoginRouteImport } from './routes/_landing/login'

const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/_landing/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoI18nRoute = DemoI18nRouteImport.update({
  id: '/demo/i18n',
  path: '/demo/i18n',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRegisterRoute = LandingRegisterRouteImport.update({
  id: '/_landing/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingLoginRoute = LandingLoginRouteImport.update({
  id: '/_landing/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LandingLoginRoute
  '/register': typeof LandingRegisterRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/': typeof LandingIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LandingLoginRoute
  '/register': typeof LandingRegisterRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/': typeof LandingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing/login': typeof LandingLoginRoute
  '/_landing/register': typeof LandingRegisterRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/_landing/': typeof LandingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/register' | '/demo/i18n' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/demo/i18n' | '/'
  id:
    | '__root__'
    | '/_landing/login'
    | '/_landing/register'
    | '/demo/i18n'
    | '/_landing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingLoginRoute: typeof LandingLoginRoute
  LandingRegisterRoute: typeof LandingRegisterRoute
  DemoI18nRoute: typeof DemoI18nRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/i18n': {
      id: '/demo/i18n'
      path: '/demo/i18n'
      fullPath: '/demo/i18n'
      preLoaderRoute: typeof DemoI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/register': {
      id: '/_landing/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof LandingRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/login': {
      id: '/_landing/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LandingLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LandingLoginRoute: LandingLoginRoute,
  LandingRegisterRoute: LandingRegisterRoute,
  DemoI18nRoute: DemoI18nRoute,
  LandingIndexRoute: LandingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
