/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LandingRouteRouteImport } from './routes/_landing/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as DemoI18nRouteImport } from './routes/demo.i18n'
import { Route as LandingWelcomeRouteImport } from './routes/_landing/welcome'
import { Route as LandingVerifyEmailRouteImport } from './routes/_landing/verify-email'
import { Route as LandingSignupRouteImport } from './routes/_landing/signup'
import { Route as LandingResendVerificationEmailRouteImport } from './routes/_landing/resend-verification-email'
import { Route as LandingLoginRouteImport } from './routes/_landing/login'
import { Route as AuthenticatedSelfRouteRouteImport } from './routes/_authenticated/self/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSelfOrganizationsRouteRouteImport } from './routes/_authenticated/self/organizations/route'
import { Route as AuthenticatedAdminRealEstateRouteRouteImport } from './routes/_authenticated/admin/real-estate/route'
import { Route as AuthenticatedSelfOrganizationsIndexRouteImport } from './routes/_authenticated/self/organizations/index'
import { Route as AuthenticatedSelfOrganizationsDashboardRouteImport } from './routes/_authenticated/self/organizations/dashboard'
import { Route as AuthenticatedSelfOrganizationsRegisterRouteRouteImport } from './routes/_authenticated/self/organizations/register/route'
import { Route as AuthenticatedSelfOrganizationsRegisterIndexRouteImport } from './routes/_authenticated/self/organizations/register/index'
import { Route as AuthenticatedAdminRealEstatePropertiesIndexRouteImport } from './routes/_authenticated/admin/real-estate/properties/index'
import { Route as AuthenticatedAdminRealEstateDashboardIndexRouteImport } from './routes/_authenticated/admin/real-estate/dashboard/index'
import { Route as AuthenticatedAdminRealEstatePropertiesLocationsIndexRouteImport } from './routes/_authenticated/admin/real-estate/properties/locations/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const DemoI18nRoute = DemoI18nRouteImport.update({
  id: '/demo/i18n',
  path: '/demo/i18n',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingWelcomeRoute = LandingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingVerifyEmailRoute = LandingVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingSignupRoute = LandingSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingResendVerificationEmailRoute =
  LandingResendVerificationEmailRouteImport.update({
    id: '/resend-verification-email',
    path: '/resend-verification-email',
    getParentRoute: () => LandingRouteRoute,
  } as any)
const LandingLoginRoute = LandingLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LandingRouteRoute,
} as any)
const AuthenticatedSelfRouteRoute = AuthenticatedSelfRouteRouteImport.update({
  id: '/self',
  path: '/self',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedSelfOrganizationsRouteRoute =
  AuthenticatedSelfOrganizationsRouteRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedSelfRouteRoute,
  } as any)
const AuthenticatedAdminRealEstateRouteRoute =
  AuthenticatedAdminRealEstateRouteRouteImport.update({
    id: '/real-estate',
    path: '/real-estate',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedSelfOrganizationsIndexRoute =
  AuthenticatedSelfOrganizationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSelfOrganizationsRouteRoute,
  } as any)
const AuthenticatedSelfOrganizationsDashboardRoute =
  AuthenticatedSelfOrganizationsDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedSelfOrganizationsRouteRoute,
  } as any)
const AuthenticatedSelfOrganizationsRegisterRouteRoute =
  AuthenticatedSelfOrganizationsRegisterRouteRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => AuthenticatedSelfOrganizationsRouteRoute,
  } as any)
const AuthenticatedSelfOrganizationsRegisterIndexRoute =
  AuthenticatedSelfOrganizationsRegisterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSelfOrganizationsRegisterRouteRoute,
  } as any)
const AuthenticatedAdminRealEstatePropertiesIndexRoute =
  AuthenticatedAdminRealEstatePropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedAdminRealEstateRouteRoute,
  } as any)
const AuthenticatedAdminRealEstateDashboardIndexRoute =
  AuthenticatedAdminRealEstateDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedAdminRealEstateRouteRoute,
  } as any)
const AuthenticatedAdminRealEstatePropertiesLocationsIndexRoute =
  AuthenticatedAdminRealEstatePropertiesLocationsIndexRouteImport.update({
    id: '/properties/locations/',
    path: '/properties/locations/',
    getParentRoute: () => AuthenticatedAdminRealEstateRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/self': typeof AuthenticatedSelfRouteRouteWithChildren
  '/login': typeof LandingLoginRoute
  '/resend-verification-email': typeof LandingResendVerificationEmailRoute
  '/signup': typeof LandingSignupRoute
  '/verify-email': typeof LandingVerifyEmailRoute
  '/welcome': typeof LandingWelcomeRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/admin/real-estate': typeof AuthenticatedAdminRealEstateRouteRouteWithChildren
  '/self/organizations': typeof AuthenticatedSelfOrganizationsRouteRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/self/organizations/register': typeof AuthenticatedSelfOrganizationsRegisterRouteRouteWithChildren
  '/self/organizations/dashboard': typeof AuthenticatedSelfOrganizationsDashboardRoute
  '/self/organizations/': typeof AuthenticatedSelfOrganizationsIndexRoute
  '/admin/real-estate/dashboard/': typeof AuthenticatedAdminRealEstateDashboardIndexRoute
  '/admin/real-estate/properties/': typeof AuthenticatedAdminRealEstatePropertiesIndexRoute
  '/self/organizations/register/': typeof AuthenticatedSelfOrganizationsRegisterIndexRoute
  '/admin/real-estate/properties/locations/': typeof AuthenticatedAdminRealEstatePropertiesLocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/about': typeof AboutRoute
  '/self': typeof AuthenticatedSelfRouteRouteWithChildren
  '/login': typeof LandingLoginRoute
  '/resend-verification-email': typeof LandingResendVerificationEmailRoute
  '/signup': typeof LandingSignupRoute
  '/verify-email': typeof LandingVerifyEmailRoute
  '/welcome': typeof LandingWelcomeRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/admin/real-estate': typeof AuthenticatedAdminRealEstateRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/self/organizations/dashboard': typeof AuthenticatedSelfOrganizationsDashboardRoute
  '/self/organizations': typeof AuthenticatedSelfOrganizationsIndexRoute
  '/admin/real-estate/dashboard': typeof AuthenticatedAdminRealEstateDashboardIndexRoute
  '/admin/real-estate/properties': typeof AuthenticatedAdminRealEstatePropertiesIndexRoute
  '/self/organizations/register': typeof AuthenticatedSelfOrganizationsRegisterIndexRoute
  '/admin/real-estate/properties/locations': typeof AuthenticatedAdminRealEstatePropertiesLocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_landing': typeof LandingRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/self': typeof AuthenticatedSelfRouteRouteWithChildren
  '/_landing/login': typeof LandingLoginRoute
  '/_landing/resend-verification-email': typeof LandingResendVerificationEmailRoute
  '/_landing/signup': typeof LandingSignupRoute
  '/_landing/verify-email': typeof LandingVerifyEmailRoute
  '/_landing/welcome': typeof LandingWelcomeRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/_landing/': typeof LandingIndexRoute
  '/_authenticated/admin/real-estate': typeof AuthenticatedAdminRealEstateRouteRouteWithChildren
  '/_authenticated/self/organizations': typeof AuthenticatedSelfOrganizationsRouteRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/self/organizations/register': typeof AuthenticatedSelfOrganizationsRegisterRouteRouteWithChildren
  '/_authenticated/self/organizations/dashboard': typeof AuthenticatedSelfOrganizationsDashboardRoute
  '/_authenticated/self/organizations/': typeof AuthenticatedSelfOrganizationsIndexRoute
  '/_authenticated/admin/real-estate/dashboard/': typeof AuthenticatedAdminRealEstateDashboardIndexRoute
  '/_authenticated/admin/real-estate/properties/': typeof AuthenticatedAdminRealEstatePropertiesIndexRoute
  '/_authenticated/self/organizations/register/': typeof AuthenticatedSelfOrganizationsRegisterIndexRoute
  '/_authenticated/admin/real-estate/properties/locations/': typeof AuthenticatedAdminRealEstatePropertiesLocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/self'
    | '/login'
    | '/resend-verification-email'
    | '/signup'
    | '/verify-email'
    | '/welcome'
    | '/demo/i18n'
    | '/admin/real-estate'
    | '/self/organizations'
    | '/admin/'
    | '/self/organizations/register'
    | '/self/organizations/dashboard'
    | '/self/organizations/'
    | '/admin/real-estate/dashboard/'
    | '/admin/real-estate/properties/'
    | '/self/organizations/register/'
    | '/admin/real-estate/properties/locations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/self'
    | '/login'
    | '/resend-verification-email'
    | '/signup'
    | '/verify-email'
    | '/welcome'
    | '/demo/i18n'
    | '/admin/real-estate'
    | '/admin'
    | '/self/organizations/dashboard'
    | '/self/organizations'
    | '/admin/real-estate/dashboard'
    | '/admin/real-estate/properties'
    | '/self/organizations/register'
    | '/admin/real-estate/properties/locations'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_landing'
    | '/about'
    | '/_authenticated/admin'
    | '/_authenticated/self'
    | '/_landing/login'
    | '/_landing/resend-verification-email'
    | '/_landing/signup'
    | '/_landing/verify-email'
    | '/_landing/welcome'
    | '/demo/i18n'
    | '/_landing/'
    | '/_authenticated/admin/real-estate'
    | '/_authenticated/self/organizations'
    | '/_authenticated/admin/'
    | '/_authenticated/self/organizations/register'
    | '/_authenticated/self/organizations/dashboard'
    | '/_authenticated/self/organizations/'
    | '/_authenticated/admin/real-estate/dashboard/'
    | '/_authenticated/admin/real-estate/properties/'
    | '/_authenticated/self/organizations/register/'
    | '/_authenticated/admin/real-estate/properties/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DemoI18nRoute: typeof DemoI18nRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/demo/i18n': {
      id: '/demo/i18n'
      path: '/demo/i18n'
      fullPath: '/demo/i18n'
      preLoaderRoute: typeof DemoI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/welcome': {
      id: '/_landing/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof LandingWelcomeRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/verify-email': {
      id: '/_landing/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof LandingVerifyEmailRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/signup': {
      id: '/_landing/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LandingSignupRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/resend-verification-email': {
      id: '/_landing/resend-verification-email'
      path: '/resend-verification-email'
      fullPath: '/resend-verification-email'
      preLoaderRoute: typeof LandingResendVerificationEmailRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/login': {
      id: '/_landing/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LandingLoginRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_authenticated/self': {
      id: '/_authenticated/self'
      path: '/self'
      fullPath: '/self'
      preLoaderRoute: typeof AuthenticatedSelfRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/self/organizations': {
      id: '/_authenticated/self/organizations'
      path: '/organizations'
      fullPath: '/self/organizations'
      preLoaderRoute: typeof AuthenticatedSelfOrganizationsRouteRouteImport
      parentRoute: typeof AuthenticatedSelfRouteRoute
    }
    '/_authenticated/admin/real-estate': {
      id: '/_authenticated/admin/real-estate'
      path: '/real-estate'
      fullPath: '/admin/real-estate'
      preLoaderRoute: typeof AuthenticatedAdminRealEstateRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/self/organizations/': {
      id: '/_authenticated/self/organizations/'
      path: '/'
      fullPath: '/self/organizations/'
      preLoaderRoute: typeof AuthenticatedSelfOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedSelfOrganizationsRouteRoute
    }
    '/_authenticated/self/organizations/dashboard': {
      id: '/_authenticated/self/organizations/dashboard'
      path: '/dashboard'
      fullPath: '/self/organizations/dashboard'
      preLoaderRoute: typeof AuthenticatedSelfOrganizationsDashboardRouteImport
      parentRoute: typeof AuthenticatedSelfOrganizationsRouteRoute
    }
    '/_authenticated/self/organizations/register': {
      id: '/_authenticated/self/organizations/register'
      path: '/register'
      fullPath: '/self/organizations/register'
      preLoaderRoute: typeof AuthenticatedSelfOrganizationsRegisterRouteRouteImport
      parentRoute: typeof AuthenticatedSelfOrganizationsRouteRoute
    }
    '/_authenticated/self/organizations/register/': {
      id: '/_authenticated/self/organizations/register/'
      path: '/'
      fullPath: '/self/organizations/register/'
      preLoaderRoute: typeof AuthenticatedSelfOrganizationsRegisterIndexRouteImport
      parentRoute: typeof AuthenticatedSelfOrganizationsRegisterRouteRoute
    }
    '/_authenticated/admin/real-estate/properties/': {
      id: '/_authenticated/admin/real-estate/properties/'
      path: '/properties'
      fullPath: '/admin/real-estate/properties/'
      preLoaderRoute: typeof AuthenticatedAdminRealEstatePropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRealEstateRouteRoute
    }
    '/_authenticated/admin/real-estate/dashboard/': {
      id: '/_authenticated/admin/real-estate/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/real-estate/dashboard/'
      preLoaderRoute: typeof AuthenticatedAdminRealEstateDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRealEstateRouteRoute
    }
    '/_authenticated/admin/real-estate/properties/locations/': {
      id: '/_authenticated/admin/real-estate/properties/locations/'
      path: '/properties/locations'
      fullPath: '/admin/real-estate/properties/locations/'
      preLoaderRoute: typeof AuthenticatedAdminRealEstatePropertiesLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRealEstateRouteRoute
    }
  }
}

interface AuthenticatedAdminRealEstateRouteRouteChildren {
  AuthenticatedAdminRealEstateDashboardIndexRoute: typeof AuthenticatedAdminRealEstateDashboardIndexRoute
  AuthenticatedAdminRealEstatePropertiesIndexRoute: typeof AuthenticatedAdminRealEstatePropertiesIndexRoute
  AuthenticatedAdminRealEstatePropertiesLocationsIndexRoute: typeof AuthenticatedAdminRealEstatePropertiesLocationsIndexRoute
}

const AuthenticatedAdminRealEstateRouteRouteChildren: AuthenticatedAdminRealEstateRouteRouteChildren =
  {
    AuthenticatedAdminRealEstateDashboardIndexRoute:
      AuthenticatedAdminRealEstateDashboardIndexRoute,
    AuthenticatedAdminRealEstatePropertiesIndexRoute:
      AuthenticatedAdminRealEstatePropertiesIndexRoute,
    AuthenticatedAdminRealEstatePropertiesLocationsIndexRoute:
      AuthenticatedAdminRealEstatePropertiesLocationsIndexRoute,
  }

const AuthenticatedAdminRealEstateRouteRouteWithChildren =
  AuthenticatedAdminRealEstateRouteRoute._addFileChildren(
    AuthenticatedAdminRealEstateRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminRealEstateRouteRoute: typeof AuthenticatedAdminRealEstateRouteRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminRealEstateRouteRoute:
      AuthenticatedAdminRealEstateRouteRouteWithChildren,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedSelfOrganizationsRegisterRouteRouteChildren {
  AuthenticatedSelfOrganizationsRegisterIndexRoute: typeof AuthenticatedSelfOrganizationsRegisterIndexRoute
}

const AuthenticatedSelfOrganizationsRegisterRouteRouteChildren: AuthenticatedSelfOrganizationsRegisterRouteRouteChildren =
  {
    AuthenticatedSelfOrganizationsRegisterIndexRoute:
      AuthenticatedSelfOrganizationsRegisterIndexRoute,
  }

const AuthenticatedSelfOrganizationsRegisterRouteRouteWithChildren =
  AuthenticatedSelfOrganizationsRegisterRouteRoute._addFileChildren(
    AuthenticatedSelfOrganizationsRegisterRouteRouteChildren,
  )

interface AuthenticatedSelfOrganizationsRouteRouteChildren {
  AuthenticatedSelfOrganizationsRegisterRouteRoute: typeof AuthenticatedSelfOrganizationsRegisterRouteRouteWithChildren
  AuthenticatedSelfOrganizationsDashboardRoute: typeof AuthenticatedSelfOrganizationsDashboardRoute
  AuthenticatedSelfOrganizationsIndexRoute: typeof AuthenticatedSelfOrganizationsIndexRoute
}

const AuthenticatedSelfOrganizationsRouteRouteChildren: AuthenticatedSelfOrganizationsRouteRouteChildren =
  {
    AuthenticatedSelfOrganizationsRegisterRouteRoute:
      AuthenticatedSelfOrganizationsRegisterRouteRouteWithChildren,
    AuthenticatedSelfOrganizationsDashboardRoute:
      AuthenticatedSelfOrganizationsDashboardRoute,
    AuthenticatedSelfOrganizationsIndexRoute:
      AuthenticatedSelfOrganizationsIndexRoute,
  }

const AuthenticatedSelfOrganizationsRouteRouteWithChildren =
  AuthenticatedSelfOrganizationsRouteRoute._addFileChildren(
    AuthenticatedSelfOrganizationsRouteRouteChildren,
  )

interface AuthenticatedSelfRouteRouteChildren {
  AuthenticatedSelfOrganizationsRouteRoute: typeof AuthenticatedSelfOrganizationsRouteRouteWithChildren
}

const AuthenticatedSelfRouteRouteChildren: AuthenticatedSelfRouteRouteChildren =
  {
    AuthenticatedSelfOrganizationsRouteRoute:
      AuthenticatedSelfOrganizationsRouteRouteWithChildren,
  }

const AuthenticatedSelfRouteRouteWithChildren =
  AuthenticatedSelfRouteRoute._addFileChildren(
    AuthenticatedSelfRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedSelfRouteRoute: typeof AuthenticatedSelfRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedSelfRouteRoute: AuthenticatedSelfRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LandingRouteRouteChildren {
  LandingLoginRoute: typeof LandingLoginRoute
  LandingResendVerificationEmailRoute: typeof LandingResendVerificationEmailRoute
  LandingSignupRoute: typeof LandingSignupRoute
  LandingVerifyEmailRoute: typeof LandingVerifyEmailRoute
  LandingWelcomeRoute: typeof LandingWelcomeRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingLoginRoute: LandingLoginRoute,
  LandingResendVerificationEmailRoute: LandingResendVerificationEmailRoute,
  LandingSignupRoute: LandingSignupRoute,
  LandingVerifyEmailRoute: LandingVerifyEmailRoute,
  LandingWelcomeRoute: LandingWelcomeRoute,
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LandingRouteRoute: LandingRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DemoI18nRoute: DemoI18nRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
