/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LandingRouteRouteImport } from './routes/_landing/route'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as DemoI18nRouteImport } from './routes/demo.i18n'
import { Route as LandingWelcomeRouteImport } from './routes/_landing/welcome'
import { Route as LandingVerifyEmailRouteImport } from './routes/_landing/verify-email'
import { Route as LandingSignupRouteImport } from './routes/_landing/signup'
import { Route as LandingResendVerificationEmailRouteImport } from './routes/_landing/resend-verification-email'
import { Route as LandingLoginRouteImport } from './routes/_landing/login'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const DemoI18nRoute = DemoI18nRouteImport.update({
  id: '/demo/i18n',
  path: '/demo/i18n',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingWelcomeRoute = LandingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingVerifyEmailRoute = LandingVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingSignupRoute = LandingSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingResendVerificationEmailRoute =
  LandingResendVerificationEmailRouteImport.update({
    id: '/resend-verification-email',
    path: '/resend-verification-email',
    getParentRoute: () => LandingRouteRoute,
  } as any)
const LandingLoginRoute = LandingLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LandingRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LandingLoginRoute
  '/resend-verification-email': typeof LandingResendVerificationEmailRoute
  '/signup': typeof LandingSignupRoute
  '/verify-email': typeof LandingVerifyEmailRoute
  '/welcome': typeof LandingWelcomeRoute
  '/demo/i18n': typeof DemoI18nRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LandingLoginRoute
  '/resend-verification-email': typeof LandingResendVerificationEmailRoute
  '/signup': typeof LandingSignupRoute
  '/verify-email': typeof LandingVerifyEmailRoute
  '/welcome': typeof LandingWelcomeRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/': typeof LandingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing': typeof LandingRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_landing/login': typeof LandingLoginRoute
  '/_landing/resend-verification-email': typeof LandingResendVerificationEmailRoute
  '/_landing/signup': typeof LandingSignupRoute
  '/_landing/verify-email': typeof LandingVerifyEmailRoute
  '/_landing/welcome': typeof LandingWelcomeRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/_landing/': typeof LandingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/resend-verification-email'
    | '/signup'
    | '/verify-email'
    | '/welcome'
    | '/demo/i18n'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/resend-verification-email'
    | '/signup'
    | '/verify-email'
    | '/welcome'
    | '/demo/i18n'
    | '/'
  id:
    | '__root__'
    | '/_landing'
    | '/about'
    | '/_landing/login'
    | '/_landing/resend-verification-email'
    | '/_landing/signup'
    | '/_landing/verify-email'
    | '/_landing/welcome'
    | '/demo/i18n'
    | '/_landing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DemoI18nRoute: typeof DemoI18nRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/demo/i18n': {
      id: '/demo/i18n'
      path: '/demo/i18n'
      fullPath: '/demo/i18n'
      preLoaderRoute: typeof DemoI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/welcome': {
      id: '/_landing/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof LandingWelcomeRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/verify-email': {
      id: '/_landing/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof LandingVerifyEmailRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/signup': {
      id: '/_landing/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LandingSignupRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/resend-verification-email': {
      id: '/_landing/resend-verification-email'
      path: '/resend-verification-email'
      fullPath: '/resend-verification-email'
      preLoaderRoute: typeof LandingResendVerificationEmailRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/login': {
      id: '/_landing/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LandingLoginRouteImport
      parentRoute: typeof LandingRouteRoute
    }
  }
}

interface LandingRouteRouteChildren {
  LandingLoginRoute: typeof LandingLoginRoute
  LandingResendVerificationEmailRoute: typeof LandingResendVerificationEmailRoute
  LandingSignupRoute: typeof LandingSignupRoute
  LandingVerifyEmailRoute: typeof LandingVerifyEmailRoute
  LandingWelcomeRoute: typeof LandingWelcomeRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingLoginRoute: LandingLoginRoute,
  LandingResendVerificationEmailRoute: LandingResendVerificationEmailRoute,
  LandingSignupRoute: LandingSignupRoute,
  LandingVerifyEmailRoute: LandingVerifyEmailRoute,
  LandingWelcomeRoute: LandingWelcomeRoute,
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LandingRouteRoute: LandingRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DemoI18nRoute: DemoI18nRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
